### ISSUE TITLE
Station User

### ISSUE THREAD

**Issue by webdeveloper001** [nowgoin/public_issue_tracker#17]
ORG ADMIN
Org admin logs into the dashboard. From the main menu, he sees a new item called Station Users
Station Users is a new page with a list of station users (similar to the Team members page). On this page, Org admin can invite / edit/archive Station users. 

On Station user create we should have two steps.
Profile information (it can be the same as Team members)
As a second step Org admin should be able to add Zones for that Station user. For the zone define widget we can use Service zone edit component

STATION USER
Stations users are being invited by org admin. When org admin invites Station user they receive set password email from Goin. 
Once they set a password they can log in to their own dashboard on Goin. 

The dashboard is a single page where they can *View trips related to their Zones. It can be the same as trip dashboard but with no option to request/change the status of trips. They should only be able to *See trips.

Backend tasks
- [x] Goin-core 	add location-user (similar to team member  https://github.com/nowgoin/goin-core/issues/234
- [x] Goin-core		location user zones model  https://github.com/nowgoin/goin-core/issues/235
- [x] Goin-trips        	get trips by given zone  https://github.com/nowgoin/goin-trip/issues/114

Frontend tasks
- [x] Location User manage page
- [x] Location user set zone page  (CRUD with map)
- [ ] Location user trip dashboard  (trip list view)
- [ ] Map view - this will show any selected trip and driver’s location if near the location zone. Maybe we fix the map to a certain zoom level. 

This is one Big-ticket for tracking overall flow. 

Temp note:
once backend tasks are finished will create corresponding frontend tasks since the frontend totally depends on the backend APIs.
